// <auto-generated />
using APP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APP.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20260405013622_CreacionTablaEstudiantes")]
    partial class CreacionTablaEstudiantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APP.Models.Estudiante", b =>
                {
                    b.Property<int>("id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_estudiante"));

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_escuela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_estudiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_estudiante");

                    b.ToTable("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
